#!/usr/bin/python


import json
import re
import sys
import os.path
import jinja2
import copy
from termcolor import colored, cprint

# Lazy way...
# Need to implement autocomplete in console.
defaultConfigPath = "/home/makjacobsen/sandbox/beemodo-server/config.json"
defaultDestinationDirectory = "/home/makjacobsen/sandbox/jinja/exports"
#defaultDestinationDirectory = "/home/makjacobsen/sandbox/jinja/resource"

class TemplateSystem:

	def __init__(self, config, templateDirectory, destinationDirectory, modelNames, templateNames):
		self.config = config
		self.templateDirectory = templateDirectory
		self.destinationDirectory = destinationDirectory
		self.modelNames = modelNames
		self.initializeTemplateEngine()
		self.initializeTemplates(templateNames)

	def initializeTemplateEngine(self):
		templateLoader = jinja2.FileSystemLoader( searchpath="" )
		self.templateEngine = jinja2.Environment( loader=templateLoader, lstrip_blocks=True, trim_blocks=True )
		self.templateEngine.filters['controller'] = self.getControllerName
		self.templateEngine.filters['singular'] = self.getSingularName
		self.templateEngine.filters['plural'] = self.getPluralName
		self.templateEngine.filters['controllerByAlias'] = self.getControllerNameByAlias
		self.templateEngine.filters['structure'] = self.getStructure
		self.templateEngine.filters['modelByAlias'] = self.getModelNameByAlias
		self.templateEngine.filters['relationships'] = self.getRelationships
		self.templateEngine.filters['models'] = self.getModelsByRelationships
		self.templateEngine.filters['mode'] = self.getMode
		self.templateEngine.filters['type'] = self.getType
		self.templateEngine.filters['validation'] = self.getValidation
		self.templateEngine.filters['camelCase'] = self.toCamelCase
		self.templateEngine.filters['snakeCase'] = self.toSnakeCase
		self.templateEngine.filters['kebabCase'] = self.toKebabCase
		self.templateEngine.filters['translation'] = self.getTranslationFields

	def initializeTemplates(self, templateNames):
		self.templates = {}
		for template in templateNames:
			self.templates[template] = self.templateEngine.get_template( self.templateDirectory + "/" + template + ".j2" )
		self.commonTemplates = {}
		self.commonTemplates["list"] = self.templateEngine.get_template( self.templateDirectory + "/common/list.j2" )
		self.commonTemplates["show"] = self.templateEngine.get_template( self.templateDirectory + "/common/show.j2" )

	def run(self):
		for modelName in self.modelNames:
			templateVars = {
					"MAIN_MODEL": modelName,
					"MODEL" : modelName,
					"CONFIG": self.config["models"]
					}
			
			# Generate common files (show.html and list.html)
			commonPath = self.destinationDirectory+"/"+modelName+"/view/common/"
			if not os.path.exists(commonPath):
					os.makedirs(commonPath)
			for template in self.commonTemplates:
				commonFile = open(commonPath + "/" + template + ".html", "w")
				commonFile.write(self.commonTemplates[template].render(templateVars))
				commonFile.close()

			# Generate files (list.html, show.html, form.html, controller.js)
			for templateType in self.templates:
				path = self.destinationDirectory+"/"+modelName
				
				if templateType == "controller":
					viewPath = path + "/controller"
					fileName = self.getControllerName(modelName) + ".js"
				else:
					viewPath = path + "/view"
					fileName = templateType + ".html"

				if not os.path.exists(path):
					os.makedirs(path)
				if not os.path.exists(viewPath):
					os.makedirs(viewPath)
				
				viewFile = open(viewPath+"/"+fileName, "w")
				viewFile.write(self.templates[templateType].render(templateVars))
				viewFile.close()

			
	# Filters

	def getControllerName(self, model):
		return model.replace("_"," ").title().replace(" ","") + "Controller"

	def getSingularName(self, model):
		return self.config["models"][model]["singular"]
	
	def getPluralName(self, model):
		return self.config["models"][model]["plural"]

	def getControllerNameByAlias(self, alias, model):
		return self.getControllerName(self.getModelNameByAlias(alias, model))
	
	def getModelNameByAlias(self, alias, model):
		return self.config["models"][model]["relationships"][alias]["type"]

	def getStructure(self, model):
		result = []
		minimum = 1000
		fieldTemp = ""
		structure = copy.deepcopy(self.config["models"][model]["structure"])
		while True:
			for field in structure:
				if(structure[field]["order"] < minimum):
					fieldTemp = field
					minimum = structure[field]["order"]
			if(len(structure)>0):
				result.append(fieldTemp)
				del structure[fieldTemp]
			if(len(structure) == 0):
				break
			else:
				minimum = 1000
		return result

	# def getStructureByAlias(self, alias, model):
	# 	return self.config["models"][self.getModelNameByAlias(alias, model)]["structure"]
	
	def getMode(self, model, field):
		return self.config["models"][model]["structure"][field]["mode"]

	def getType(self, model, field):
		return self.config["models"][model]["structure"][field]["type"]

	def getValidation(self, model, field):
		return self.config["models"][model]["structure"][field]["validation"]
	
	def getRelationships(self, model, isArray):
		relationships = copy.deepcopy(self.config["models"][model]["relationships"])
		newRelationships = {}
		for relationship in relationships:
			if relationships[relationship]["isArray"] == isArray:
				newRelationships[relationship] = relationships[relationship]

		result = []
		minimum = 1000
		aliasTemp = ""
		while True:
			for alias in newRelationships:
				if(newRelationships[alias]["order"] < minimum):
					aliasTemp = alias
					minimum = newRelationships[alias]["order"]
			if(len(newRelationships)>0):
				result.append(aliasTemp)
				del newRelationships[aliasTemp]
			if(len(newRelationships) == 0):
				break
			else:
				minimum = 1000

		return result

	
	def getModelsByRelationships(self, relationships):
		models = []
		for model in relationships:
			models.append(relationships[model]["type"])
		return models
	
	def getTranslationFields(self, model):
		fields = {}
		for field in self.config["models"][model]["structure"]:
			if self.config["models"][model]["structure"][field]["translation"] == True:
				fields[field] = self.config["models"][model]["structure"][field]
		return fields
	
	def toCamelCase(self, string):
		string = self.toSnakeCase(string)
		string = string.replace("_"," ").title().replace(" ","")
		return string[:1].lower() + string[1:]

	def toKebabCase(self, string):
		string = self.toSnakeCase(string)
		return string.lower().replace("_","-")

	def toSnakeCase(self, string):
		string = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', string)
		return re.sub('([a-z0-9])([A-Z])', r'\1_\2', string).lower()


class HookStudIoPromt:

	def __init__(self, systemName):
		self.systemName = systemName.title()
		self.welcomeColor = "cyan"
		self.outputColor = "white"
		self.promtColor = "grey"

	def printWelcome(self):
		title = "Welcome to HookStud.io {} System".format(self.systemName)
		print("")
		cprint("="*len(title), self.welcomeColor, attrs=["bold"])
		cprint(title, self.welcomeColor, attrs=["bold"]) 
		cprint("="*len(title), self.welcomeColor, attrs=["bold"]) 

	def input(self):
		cprint("HookStud.io $", self.promtColor, attrs=['bold'], end=" ")
		return raw_input()
	
	def output(self, message):
		print("")
		cprint(message, self.outputColor, attrs=["bold"])

	def error(self, message):
		print("")
		cprint(message, "red", attrs=["bold"])

	def success(self, message):
		print("")
		cprint(message, "green", attrs=["bold"])

class ScaffoldingPromtSystem:

	def __init__(self):
		self.promt = HookStudIoPromt("scaffolding")
		self.promt.printWelcome()
	
	def step1(self):
		self.promt.output("1. Enter the configuration.json path. ( optional - if omitted the path will be set to  " + defaultConfigPath + ")")
		
		configPath = self.promt.input()
		
		# Remove this when autocomplete in console is implemented.
		if configPath == "":
			configPath = defaultConfigPath

		if not os.path.isfile(configPath):
			self.promt.error("Error: The file doesn't exists.")
			self.step1()
		elif configPath[-5:] != ".json":
			self.promt.error("Error: The configuration file must be in .json format.")
			self.step1()
		else:
			with open(configPath) as jsonFile:
				self.config = json.load(jsonFile)

	def step2(self):
		self.promt.output("2. Enter the template directory. ( optional - if omitted the directory will be set to \"./templates\" )")
		
		templateDirectory = self.promt.input()
		
		if templateDirectory == "":
			self.templateDirectory = "./templates"
		else:
			self.templateDirectory = templateDirectory

	def step3(self):
		self.promt.output("3. Enter the destination directory. ( optional - if omitted the directory will be set to " + defaultDestinationDirectory + " )")
		
		destinationDirectory = self.promt.input()

		if destinationDirectory == "":
			self.destinationDirectory = defaultDestinationDirectory
		else:
			if os.path.exists(destinationDirectory):
				self.promt.error("The destination directory already exists. Do you want to overwrite? y/n")
				action = self.promt.input()
				if(action == "y"):
					self.destinationDirectory = destinationDirectory
				else:
					self.step3()

	def step4(self):
		self.promt.output("4. Enter the model names seperated by \",\" ( optional - if omitted every models in configurations.json will be scaffolded. )")
		
		modelNames = self.promt.input()
		
		if modelNames == "":
			self.modelNames = [name for name in self.config["models"]]
		else:
			self.modelNames = [name.strip() for name in modelNames.split(',')]
			for name in self.modelNames:
				if name not in self.config["models"]:
					self.promt.error("Error: Some of the models doesn't exists in the configurations.json")
					self.step4()

	def step5(self):
		self.promt.output("5. Enter the template names seperated by \",\" ( optional - if omitted \"list,show,form,controller\" will be used. )")
		
		templateNames = self.promt.input()
		defaultTemplateNames = ["list", "show", "form", "controller"]

		if templateNames == "":
			self.templateNames = defaultTemplateNames
		else:
			self.templateNames = [name.strip() for name in templateNames.split(',')]
			for name in self.templateNames:
				if name not in defaultTemplateNames:
					self.promt.error("Error: Some of the template names doesn't exists")
					self.step5()

	def finish(self):
		self.promt.success("Successful Scaffolding!")
		print("")

	def run(self):
		self.step1()
		self.step2()
		self.step3()
		self.step4()
		self.step5()
		self.finish()

if __name__ == '__main__':
	
	scaffoldPromt = ScaffoldingPromtSystem()
	
	while(True):
		scaffoldPromt.run()

		config = scaffoldPromt.config
		templateDirectory = scaffoldPromt.templateDirectory
		destinationDirectory = scaffoldPromt.destinationDirectory
		modelNames = scaffoldPromt.modelNames	
		templateNames = scaffoldPromt.templateNames

		templateSystem = TemplateSystem(config, templateDirectory, destinationDirectory, modelNames, templateNames)
		templateSystem.run()
